---
services:
  - docker
dist: focal
sudo: required
git:
  depth: false
language: go
go:
  - 1.12.x
script:
  - sudo apt update && sudo apt install docker.io
  - docker version
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - docker version
  - make docker-build

# after_success:
#   - bash <(curl -s https://codecov.io/bash) || echo "Failed to report code coverage!"
